# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_Comentario', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_Contacto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
                ('apellidoM', models.CharField(max_length=45)),
                ('apellidoP', models.CharField(max_length=45)),
                ('cargo', models.CharField(blank=True, max_length=30, null=True)),
                ('comentarios', models.ManyToManyField(to='aplicacionobmex.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_Curso', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('hora', models.TimeField()),
                ('costo', models.FloatField()),
                ('instructor', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_Direccion', models.IntegerField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=25)),
                ('entidad', models.CharField(max_length=30)),
                ('delegacion', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('numero_2', models.CharField(max_length=30)),
                ('entreCalle_1', models.CharField(max_length=30)),
                ('entreCalle_2', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('AS', 'Aguascalientes'), ('BC', 'Baja California'), ('BS', 'Baja California Sur'), ('CC', 'Campeche'), ('CS', 'Chiapas'), ('CH', 'Chihuahua'), ('CX', 'Ciudad de Mexico'), ('CL', 'Coahuila'), ('CM', 'Colima'), ('DG', 'Durango'), ('EM', 'Estado de Mexico'), ('GT', 'Guanajuato'), ('GR', 'Guerrero'), ('HG', 'Hidalgo'), ('JC', 'Jalisco'), ('MN', 'Michoacan'), ('MS', 'Morelos'), ('NT', 'Nayarit'), ('NL', 'Nuevo Leon'), ('OC', 'Oaxaca'), ('PL', 'Puebla'), ('QT', 'Queretaro'), ('QR', 'Quintana Roo'), ('SP', 'San Luis Potosi'), ('SL', 'Sinaloa'), ('SR', 'Sonora'), ('TC', 'Tabasco'), ('TS', 'Tamaulipas'), ('TL', 'Tlaxcala'), ('VZ', 'Veracruz'), ('YN', 'Yucatan'), ('ZS', 'Zacatecas')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_Institucion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('rfc', models.CharField(blank=True, max_length=16, null=True)),
                ('contacto', models.ManyToManyField(to='aplicacionobmex.Contacto')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_Producto', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('enstock', models.BooleanField(default=True)),
                ('existencias', models.IntegerField(blank=True)),
                ('maxStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_Pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('monto', models.FloatField()),
                ('tipoSilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_Telefono', models.IntegerField(primary_key=True, serialize=False)),
                ('lada', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField()),
                ('extencion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='institucion',
            name='pedido',
            field=models.ManyToManyField(to='aplicacionobmex.Pedido'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Telefono'),
        ),
        migrations.AddField(
            model_name='curso',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Direccion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='participantes',
            field=models.ManyToManyField(to='aplicacionobmex.Contacto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='cursos',
            field=models.ManyToManyField(to='aplicacionobmex.Curso'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='pedido',
            field=models.ManyToManyField(to='aplicacionobmex.Pedido'),
        ),
    ]
