# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellidoM',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellidoP',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='aplicacionobmex.Comentario'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='aplicacionobmex.Curso'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='pedido',
            field=models.ManyToManyField(blank=True, to='aplicacionobmex.Pedido'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='direccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Direccion'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='aplicacionobmex.Contacto'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='delegacion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='entidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='entreCalle_1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='entreCalle_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='contacto',
            field=models.ManyToManyField(blank=True, to='aplicacionobmex.Contacto'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Direccion'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='pedido',
            field=models.ManyToManyField(blank=True, to='aplicacionobmex.Pedido'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='telefono',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Telefono'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='maxStock',
            field=models.IntegerField(blank=True),
        ),
    ]
