# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0003_auto_20170709_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='generacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], unique=True),
        ),
    ]
