# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0004_auto_20170807_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='telefono',
        ),
        migrations.AddField(
            model_name='telefono',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Institucion'),
        ),
    ]
