# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0004_auto_20170709_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Telefono'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='contacto',
            field=models.ManyToManyField(blank=True, null=True, to='aplicacionobmex.Contacto'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Direccion'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='pedido',
            field=models.ManyToManyField(blank=True, null=True, to='aplicacionobmex.Pedido'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Telefono'),
        ),
    ]
