# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0005_auto_20170721_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
