# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0006_pedido_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='contacto',
            field=models.ManyToManyField(blank=True, to='aplicacionobmex.Contacto'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='pedido',
            field=models.ManyToManyField(blank=True, to='aplicacionobmex.Pedido'),
        ),
    ]
