# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0007_auto_20170721_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='telefono',
        ),
    ]
