# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0010_auto_20170721_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='id_Telefono',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
