# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0010_auto_20170721_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellidoM',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellidoP',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacionobmex.Telefono'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='id_Telefono',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
