# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0012_areglar relaciones de base de datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(default='0', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.CharField(max_length=13),
        ),
    ]
