# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionobmex', '0011_auto_20170721_2355'),
        ('aplicacionobmex', '0013_se agrego el campo tipo en telefono, arreglar relaciones de base de datos'),
    ]

    operations = [
    ]
